### PR TITLE
don't use sharedInstance as it doesn't behave well when app backgrounded

### PR DESCRIPTION
**Pull request by danlannz**
@jamiltz

### CODE REVIEW

**Comment by rghorbani** [comment]
Good advice!

**Comment by npomfret** [comment]
@rghorbani can you elaborate?  And could you give some alternative code?

**Comment by npomfret** [comment]
@DanlanNZ can you elaborate?  And could you give some alternative code?

**Comment by GermanMontejo** [comment]
@DanlanNZ hi. awesome job in fixing this issue with ios. I too have experienced the problem wherein couchbase can't pull the data after several minutes of being idled. This PR coupled with https://github.com/couchbaselabs/react-native-couchbase-lite/pull/124 fixed my issue. One thing though, could you address the conflicts? Thanks a lot!

**Comment by jamesnocentini** [comment]
fixed the conflict locally and pushed to master. Again, thanks for this PR and testing the fix! I'll close this PR.

**Pull request closed without merging**
