### PR TITLE
Change version tag following React Native Podspec

### PR DESCRIPTION
**Pull request by adamski**
Remove comments and copy the format of the React Native Podspec in terms of the version number.

### CODE REVIEW

**Comment by adamski** [comment]
This pull request needs to go along with a build script e.g. https://github.com/facebook/react-native/blob/master/scripts/bump-oss-version.js#L49
Will update if/when I get the chance.

**Comment by pasin** [comment]
@jamiltz Can you look at this PR?

**Comment by jamesnocentini** [comment]
@adamski that looks great! we need to run that build script and it will automatically update the podspec? can you describe the publishing flow for bumping the version number a little? I'm not sure what to do.

**Comment by adamski** [comment]
Hi I haven't tried it yet myself! I think it might need some adjustment for this project, I was just trying to see how RN did their automatic version updating for Podspec, gradle and npm.

**Comment by jamesnocentini** [comment]
Thanks @adamski. Let's keep this PR open for now. We need to look into the script further and how to use it.

**Comment by adamski** [comment]
I created [podspec-generator](https://github.com/adamski/podspec-generator) to solve the problem in a more general way, as many react-native modules do not include a Podspec at all. It could be used as part of a build script to generate the Podspec before publishing.

**Comment by jamesnocentini** [comment]
Closing this PR, the recommended way of adding the module is through react-native link https://github.com/couchbaselabs/react-native-couchbase-lite#installation

**Comment by adamski** [comment]
Although I'm not using this module anymore, some people may still need to use Cocoapods to install it. 
I'm working on a [fork](https://github.com/adamski/react-native-couchbase) of another couchbase-lite module that takes a more native approach, and I just committed a dynamic podspec file: https://github.com/adamski/react-native-couchbase/blob/master/ReactNativeCouchbase.podspec

**Comment by jamesnocentini** [comment]
> I'm working on a fork of another couchbase-lite module that takes a more native approach

Have you seen https://groups.google.com/forum/#!topic/mobile-couchbase/4B6RDHriNak? It's for 2.0 which isn't GA yet. But ultimately if there are JavaScript bindings for Couchbase Lite Core it might be usable in react native apps.

> and I just committed a dynamic podspec file: https://github.com/adamski/react-native-couchbase/blob/master/ReactNativeCouchbase.podspec

Thanks!

**Comment by adamski** [comment]
Ah, yes bypassing the platform-specific layer like that would be ideal - I’ve had a look at the example React Native cxxreact module, and wrapping LiteCore in such a module makes a lot of sense.

**Pull request closed without merging**
