### PR TITLE
Change notification endpoint

### PR DESCRIPTION
**Pull request by jamesnocentini**
Add the _changes endpoint and send the notifications to the app using EventEmitter.

### CODE REVIEW

**Comment by jamesnocentini** [comment]
Todo: add the usage of this endpoint in the sample app (in the `ReactNativeCouchbaseLiteExample` directory) before merging.

**Comment by jamesnocentini** [comment]
@blairio @npomfret take a look at this and whether it aligns with what you expect from the listener changes api. Thanks

**Comment by blairio** [comment]
listen() is defined twice

**Comment by blairio** [comment]
Starting the cseq at 0 every time I think might replay all the changes ever to the DB whenever your start up and call listen() for the first time.

Does it matter that the headers that are set in _makeRequest are not being used? 
Although Using XMLHttpRequest might be nice because I think you could abort a request if you wanted to stop listening.

**Comment by jamesnocentini** [comment]
Thanks @blairio. I added a param to specify the sequence number to start from so the user can choose. As you pointed out, the auth header was missing so I added that one too and ReactNativeCouchbaseLiteExample for android now has the line `The database sequence: ...`.

**Pull request merged**
